"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import glob

APP = ['main.py']
# DATA_FILES = [ ('app', glob.glob('app/*.*')) , ('tests', glob.glob('tests/*.*')) , "dualem-data.txt", "gps-data.txt", "server.py", "tests_main.py"]
# DATA_FILES = [ 'app', 'tests', "dualem-data.txt", "gps-data.txt", "server.py", "tests_main.py"]
DATA_FILES = [ "dualem-data.txt", "gps-data.txt", "server.py", "tests_main.py"]

OPTIONS = {
    'iconfile':'logo.ico',
    'packages': ['flask', 'werkzeug', 'jinja2'],
    'resources': ['./app/static', './app/templates', './app/__init__.py','./app/routes.py'],
}
setup(
    app=APP,
    name="emi-toolkit",
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    #packages=['Flask','Flask-jsglue', 'json', 'pathlib']
)
