""" map table

Revision ID: 370032b78318
Revises: 
Create Date: 2021-09-23 16:46:50.580940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '370032b78318'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mapName', sa.String(length=100), nullable=True),
    sa.Column('mapPath', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_map_mapName'), 'map', ['mapName'], unique=True)
    op.create_index(op.f('ix_map_mapPath'), 'map', ['mapPath'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_map_mapPath'), table_name='map')
    op.drop_index(op.f('ix_map_mapName'), table_name='map')
    op.drop_table('map')
    # ### end Alembic commands ###
